### ISSUE TITLE
Flaky spec: Proposals Voting Voting proposals on behalf of someone in show view

### ISSUE THREAD

**Issue by aitbw** [consul/consul#2558] opened 2018-03-28 00:07 UTC
# What

Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 52051

**Travis failed build:** [Travis build 20903, job 1](https://travis-ci.org/consul/consul/jobs/359034088)

**Failure:**

```
  2) Proposals Voting Voting proposals on behalf of someone in show view
     Failure/Error: expect(page).to have_content "1 support"
       expected to find text "1 support" in "Language: English Español Français Nederlands Português CONSUL MANAGEMENT Users Edit user account Create proposal Support proposals Create spending proposal Support spending proposals Create budget investment Support Budget Investments Print Budget Investments Print proposals Print spending proposals User's invites Change user Identified as: Username: Manuela2999 Email: manuela3047@consul.dev Document type: DNI Document number: 00000101X Print this info Go back Proposal 266 title Manuela2998 • 2018-03-27 • No comments • Proposal code: MAD-2018-03-1 In summary, what we want is... 278 Proposal description Additional documentation http://external_documention.es External video https://youtu.be/nhuNb0XtRhQ Proposal question Documents (0) All city Related content (0) Add related content SUPPORTS 0% / 100% No supports 53,726 supports needed Support SHARE twitter facebook google_plus FOLLOW Follow citizen proposal COMMUNITY Participate in the user community of this proposal. Access the community Comments (0) Notifications (0) Sort by Most voted Newest first Leave your comment"
     # ./spec/features/management/proposals_spec.rb:164:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- [How to Deal With and Eliminate Flaky Tests - Semaphore](https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests)

### Final thoughts
The true objective of this issue is not "to fix" a flaky spec, but to change a spec that randomly fails into one that we can trust when it passes (or fails). 

That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".

Sometimes the fix is to re-write the entire tests with a different approach, or to extend an existing spec. Tests are sometimes written without taking a look at other tests files neither near scenarios.

### To consider

* This flaky is only occurring in CONSUL, so you might check [Decide Madrid](http://github.com/AyuntamientoMadrid/consul) specs as a start

* This issue came up first in #2534

* [This test](https://github.com/consul/consul/blob/master/spec/features/management/proposals_spec.rb#L140) might be a suspicious flaky as well

**Comment by javierv** [comment] 2018-06-23 20:17
I get the failure quite often by running `bundle exec rspec spec/features/management/proposals_spec.rb --seed 8625`. Running the test standalone I don't get the failure as often.

Running the application in development, however, I always get a 500 error by clicking the "Support" link as the default manager user. So far I see the behaviour is different because in the tests `managed_user` is assigned in the `login_managed_user` method. Does it happen to anyone else, or is it just my development environment?

**Comment by cheneyshreve** [comment] 2018-06-23 21:00
Hi @javierv, thanks for your follow-up. Unfortunately, I just ran the spec you mention above (bundle exec rspec spec/features/management/proposals_spec.rb --seed 8625) and I get 11 examples, 0 failures so I am not able to reproduce the errors you are seeing. But perhaps someone else will chime in who has seen the error too because it could easily be a difference in environment setup.

**Comment by MariaCheca** [comment] 2018-08-10 11:14
Closed via https://github.com/consul/consul/pull/2697

**Closed by MariaCheca** 2018-08-10 11:14 UTC
