### ISSUE TITLE
Admin newsletters: send a maximum number of emails at a time

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2473] opened 2018-02-19 19:54 UTC
This issue is related to https://github.com/consul/consul/issues/2318 **and must be performed after it's done.**

Let the newsletters mailer send a maximum number of emails at a time to prevent being identified as spam in case there are too much emails being sent at the same time.

**Comment by bertocq** [comment] 2018-02-20 18:18
Do some research around the idea behind https://stackoverflow.com/questions/42366391/how-to-send-mails-to-5-user-per-minute-using-delayed-job/42367624#42367624

**Comment by javierm** [comment] 2019-11-18 17:26
Issue #2623, which was closed via #2802, was a duplicate of this one, so I'm closing this one too.

**Closed by javierm** 2019-11-18 17:26 UTC
Labels: Newsletters
