### ISSUE TITLE
Adds milestones to legislation processes

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2743] opened 2018-07-09 16:15 UTC
Background
==

Now on the budget investments, the admin can include milestones to allow the following of the evolution of the project on `/admin/budgets/X/budget_investments/N/budget_investment_milestones/new`

What we need
==

Include this feature in legislation processes:

- Include a new tab "Following" on admin panel in `/admin/legislation/processes/N/edit` _[Screenshot_1]_

- Also, include on this tab a "Following of process" CKEditor textarea _[Screenshot_1]_

- New legislation process milestone form (like `/admin/budgets/X/budget_investments/N/budget_investment_milestones/new`)  _[Screenshot_2]_

- Include the "Following of process" text and legislation process milestones on front view (use the date of the last milestone)  _[Screenshot_3]_

Screenshots
==
**[Screenshot_1]**
![lp1](https://user-images.githubusercontent.com/631897/42507451-86c59e7a-8445-11e8-9455-abb4ddbee749.jpg)

**[Screenshot_2]**
![lp2](https://user-images.githubusercontent.com/631897/42507455-88884fd2-8445-11e8-96e2-a12fbd7e8007.jpg)

**[Screenshot_3]**
![lp3](https://user-images.githubusercontent.com/631897/42507728-78451ffa-8446-11e8-98f2-0f5928d543a5.jpg)

**Comment by mlovic** [comment] 2018-07-13 10:48
I'll do this one

**Comment by mlovic** [comment] 2018-07-13 11:12
After looking at the code, I just want to make sure that these milestones will be independent from the Budget::Investment milestones (different model, different DB table, mostly different view partials, etc.) @decabeza

**Comment by voodoorai2000** [comment] 2018-07-13 11:38
@mlovic there is no difference between the attributes for a budget milestone and a legislation milestone, so this sounds like a polymorphic relationship 👌

**Comment by aitbw** [comment] 2018-07-13 11:46
That being the case, and considering #2740, I think it would be better to develop a polymorphic `milestone` model before tackling this issue

**Comment by voodoorai2000** [comment] 2018-07-13 12:11
+1 Here goes the issue https://github.com/consul/consul/issues/2763

**Comment by mlovic** [comment] 2018-07-13 12:14
@voodoorai2000  Okay, wasn't sure if the "no difference" was by design or by coincidence. So I guess all types of milestone will have the same `max_title_length`, `max_num_documents`, etc.

I'll call the relationship `milestoneable`, unless there is a better suggestion.

(One difference is that a investment milestone also `belongs_to` a `Budget::Investment::Status`.)

@aitbw Didn't see that, thanks!

**Comment by mlovic** [comment] 2018-07-13 12:16
@voodoorai2000 Just saw the new issue, got it :+1:

**Comment by voodoorai2000** [comment] 2018-07-13 12:28
Sure, [Budget::Investment::Status](https://github.com/consul/consul/pull/2705) should also be made part of this polymorphic relationship, they are just names for types of milestones (contract open, in execution, executed, etc). Maybe something like `Milestone::Status` works nicely

I guess at some point, it will make sense to differentiate the `status` for each resource (Proposals, Investments, Legislations). Legislations might have (drafting, final revision available, voting in congress, voting in senate) but for now, I would keep it as simple as possible, displaying them all together independently of their class 😌

**Closed** 2018-12-12 14:12 UTC
Labels: Admin, Backport, Legislation
