### ISSUE TITLE
How to register social close send email confirm.

### ISSUE THREAD

**Issue by Chanachai-Pansailom** [consul/consul#4886] opened 2022-08-02 02:43 UTC
(How to register social close send email confirm)
The email verification system will be disabled when registering via social media.

**Comment by javierm** [comment] 2022-08-02 10:07
Hi, @Chanachai-Pansailom :smile:.

The email confirmation isn't used if it has already been confirmed by the social media. The goal of the email confirmation is to make sure the email belongs to the person who's registering, so if that person has already confirmed their email using social media, we don't ask for the same confirmation.

**Comment by javierm** [comment] 2022-09-08 20:36
Closing since this is the expected behaviour. @Chanachai-Pansailom Feel free to reopen if the comment above doesn't solve your issue :wink:.

**Closed by javierm** 2022-09-08 20:36 UTC
