### ISSUE TITLE
Allow to hide proposals created by admin

### ISSUE THREAD

**Issue by artofhuman** [consul/consul#1794] opened 2017-08-08 18:07 UTC
Hi, I have proposals created by admin and want to hide one of them, but in moderation section in the admin, i don`t see proposals. When I dig a code I found proposal not loaded for the current admin user.

```ruby
@resources = resource_model.accessible_by(current_ability, :moderate)
```
``` sql
"SELECT \"proposals\".* FROM \"proposals\" WHERE \"proposals\".\"hidden_at\" IS NULL AND (not (\"proposals\".\"author_id\" = 1))"
```

**Comment by decabeza** [comment] 2017-08-09 08:56
Hi @artofhuman 

In Moderation section `(/moderation)` only appears the proposals marked as flagged.

You can **hide a proposal** on front side with the `Hide` link. (Logged as mod@consul.dev, because an admin can't delete item created by themselves)

![hide_proposal](https://user-images.githubusercontent.com/631897/29113305-f7957376-7cf0-11e7-91e4-e34b9dda4591.jpg)

**Comment by artofhuman** [comment] 2017-08-09 09:05
> because an admin can't delete item created by themselves

I don't understand why. If I admin, why I can`t hide my proposal. I think admin should have all privileges.

**Comment by SrinandanPai** [comment] 2019-04-18 22:57
@decabeza I am a ROR developer and I am new to open source. Can I work on this?

**Comment by decabeza** [comment] 2019-04-19 12:40
🎉 Of course @SrinandanPai! All yours 🙏 😌

**Comment by javierm** [comment] 2019-11-09 21:33
@SrinandanPai Are you still working on this issue? If you need any help, feel free to ask :smile:.

If you aren't working on this issue anymore, it's fine :wink:, thanks for being interested in contributing to CONSUL anyway :pray:.

**Comment by SrinandanPai** [comment] 2019-11-11 18:03
I thought the issue was resolved.
Update on my development: I had fixed the bug locally and tested manually but wasn't able to run the unit test cases. 
If the issue is still open then I would love to contribute. My apologies if I had caused any inconvenience.

**Comment by javierm** [comment] 2019-11-11 18:47
@SrinandanPai No inconveniences at all! :smile:. Feel free to keep working on this issue :wink:.

**Comment by SrinandanPai** [comment] 2019-12-12 14:14
@javierm  I have raised PR(https://github.com/consul/consul/pull/3884). Let me know if I have missed anything.

**Closed** 2020-03-26 14:07 UTC
Labels: Good first issue, help wanted
