### ISSUE TITLE
Return 404 instead of 500 error when budget url is invalid

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2365] opened 2018-01-23 12:14 UTC
If a non existing budget url is requested, return a 404 error instead of the current 500.

For example  accesing `localhost:3000/budgets/r/n`

**Comment by raul-fuentes** [comment] 2018-01-24 10:33
I'll do this one

**Comment by raul-fuentes** [comment] 2018-01-24 11:28
The problem is currently solved, I think

- budget not fount 
![screenshot from 2018-01-24 12 24 13](https://user-images.githubusercontent.com/33748390/35329923-d6dc6564-0101-11e8-87cf-e07a5ae0c338.png)

- budget investment not fount
![screenshot from 2018-01-24 12 23 54](https://user-images.githubusercontent.com/33748390/35329922-d6c32b1c-0101-11e8-9ec2-84c532cdf02a.png)

**Comment by bertocq** [comment] 2018-01-24 11:30
@raul-fuentes please try suggested route in issue description `localhost:3000/budgets/r/n`

**Comment by bertocq** [comment] 2018-01-24 11:31
![screen shot 2018-01-24 at 12 31 33](https://user-images.githubusercontent.com/983242/35330103-88b433de-0102-11e8-97ab-ed79a1bf657d.jpg)
![screen shot 2018-01-24 at 12 31 29](https://user-images.githubusercontent.com/983242/35330104-88d799be-0102-11e8-9759-b0fcaadfa6fa.jpg)

**Comment by raul-fuentes** [comment] 2018-01-24 11:42
Also work's

![screenshot from 2018-01-24 12 31 48](https://user-images.githubusercontent.com/33748390
/35330473-de689ecc-0103-11e8-8319-ca0f96d8680c.png)

**Comment by MariaCheca** [comment] 2018-01-24 11:44
Looks like it's something happening only in https://github.com/ayuntamientomadrid/consul due to some differences with the route paths. @raul-fuentes feel free to investigate there :)

**Comment by raul-fuentes** [comment] 2018-01-24 11:47
I'm going to check it there

**Comment by voodoorai2000** [comment] 2018-05-31 20:28
Indeed, this problem is related to customs routes used in Madrid's fork
Probably some bot accessing random urls, closing for now.

**Closed by voodoorai2000** 2018-05-31 20:28 UTC
Labels: Budget, In-progress
