### ISSUE TITLE
Bug report: Adding a custom content block in side block of budget investment prevents users from voting.

### ISSUE THREAD

**Issue by TomClive** [consul/consul#5035] opened 2022-11-25 11:33 UTC
As in the title, if you add a custom content block to a budget it prevents the voting function from working.

Please check this example.
https://dev.communitychoices.scot/budgets/36/investments
![image](https://user-images.githubusercontent.com/9372488/203975659-ecd60051-d29f-4a0b-a3c6-f60bf06b7c9e.png)

When you click on the vote button nothing happens.

This is what we see in the Console using Chrome Dev Tools.
![image](https://user-images.githubusercontent.com/9372488/203976322-bd6ad709-dda4-4518-b777-f5ed8e9cc294.png)

If we remove the content block, the voting functions works perfectly.

We have tested this on a direct fork of Consul release 1.5 without any modifications by us.

The custom content block is a list but this happens even if you only add a single line of text.

**Comment by coslajohn** [comment] 2022-11-25 11:35
The vote/action is actually registered but the view is not refreshed until the browser itself is refreshed

**Comment by javierm** [comment] 2022-11-25 12:48
I can reproduce this bug. We'll have a look.

By the way, while it isn't the cause of this bug, I've noticed the example page you're linking to [uses invalid HTML](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fdev.communitychoices.scot%2Fbudgets%2F36%2Finvestments) in its content block. A current limitation of content blocks is they're inside a `<ul>` tag, so all its direct children need to be `<li>` tags.

**Comment by coslajohn** [comment] 2022-11-25 12:54
> I can reproduce this bug. We'll have a look.
> 
> By the way, while it isn't the cause of this bug, I've noticed the example page you're linking to [uses invalid HTML](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fdev.communitychoices.scot%2Fbudgets%2F36%2Finvestments) in its content block. A current limitation of content blocks is they're inside a `<ul>` tag, so all its direct children need to be `<li>` tags.

Thanks for clarifying this @javierm 
the guidance on the custom blocks page isn't clear that the <ul> tag is required and could imply that the <ul> is being added automatically
Information about content blocks
**You can create HTML content blocks that can be inserted in different places of your website.

A content block is a group of links, and it must have the following format:

<li><a href="http://site1.com">Site 1</a></li>
<li><a href="http://site2.com">Site 2</a></li>
<li><a href="http://site3.com">Site 3</a></li>**

**Comment by javierm** [comment] 2022-11-28 12:27
I wonder whether it even makes sense to use `<ul>` tags with `<li>` children in the case of budget heading content blocks :thinking:. The problem now is that, if we remove the `<ul>` tags, existing content blocks using `<li>` tags will be invalid, so changing this behaviour it tricky.

**Closed as completed** 2022-11-28 17:09 UTC
Labels: Bug
