### ISSUE TITLE
hardcoded "spanish" language in module Searchable

### ISSUE THREAD

**Issue by milovanderlinden** [consul/consul#3294] opened 2019-02-13 01:34 UTC
The file **app/models/concern/searchable.rb** uses a dictionary that is set to spanish. This should be configurable.

```ruby
module Searchable
  extend ActiveSupport::Concern

  included do
    include PgSearch
    include SearchCache

    pg_search_scope :pg_search, {
      against: :ignored, # not used since using a tsvector_column
      using: {
        tsearch: { tsvector_column: 'tsv', dictionary: "spanish", prefix: true }
      },
      ignoring: :accents,
      ranked_by: '(:tsearch)',
      order_within_rank: (column_names.include?('cached_votes_up') ? "#{table_name}.cached_votes_up DESC" : nil)
    }
  end

end
```

**Comment by katafrakt** [comment] 2019-10-09 09:12
Hi! CodeTriage sent me here ;) I think this can be fixed in at least 3 ways:
* Set in some config file (I guess Consul does not have one for now?)
* Taken from i18n
* Taken from dynamic configuration in admin panel

Which would be the best? If one is chosen, I can work on that, I guess.

**Comment by javierm** [comment] 2019-10-19 03:19
Duplicate of #730.

**Closed by javierm** 2019-10-19 03:19 UTC

**Comment by javierm** [comment] 2019-10-19 03:34
@katafrakt Thanks for offering! Maybe we could start by basing it on `I18n.default_locale`. It that doesn't seem the most simple solution to you, let us know!

(By the way, copying this comment on #730 to continue the conversation in the original issue).
