### ISSUE TITLE
Show investment's map at Budget's heading page

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2430] opened 2018-02-03 17:26 UTC
Background
==

At the list of investments for a given Budget Heading, show a map with geolocated ones in the header banner

For example at `http://localhost:3000/budgets/2/investments?filter=not_unfeasible&heading_id=10` or `https://decide.madrid.es/presupuestos/presupuestos-participativos-2018/distritos/barajas`

What we need
==

Include a map in the header showing only the geolocated projects on current heading.

**Notes**

For the example on the screenshot I used:
- A `small-12 medium-8 column` class for map container.
- A `max-height: $line-height * 10` style for map container.

Screenshot
==

![header_map](https://user-images.githubusercontent.com/631897/35815394-a61e7944-0a98-11e8-86c8-bf6353132b1a.jpg)

**Comment by iagirre** [comment] 2018-02-14 12:30
I'll do this one.

**Comment by bertocq** [comment] 2018-03-01 12:29
@iagirre have you started working on this one? (please push or reference a branch if so) Or can we liberate it?

**Comment by iagirre** [comment] 2018-03-01 12:38
Yes, I started here https://github.com/wairbut-m2c-aytomadrid/consul/tree/2430-show-map-in-budget-heading-header.
I encountered [a problem](https://travis-ci.org/wairbut-m2c-aytomadrid/consul/jobs/342264016#L2074) running one of the tests ([this one](https://github.com/AyuntamientoMadrid/consul/blob/master/spec/features/budgets/ballots_spec.rb#L267)). I [rewrote](https://github.com/AyuntamientoMadrid/consul/commit/27200910dd9e619ed482fa772fc50e158ea73432) that spec to avoid the use of JS, but I was waiting for some feedback in slack to know if this was a good approach.
The problem is (summarized) that when running this test, when it makes the second visit the map is already initialized. I don't really need the map painted there because it's something I already test in another spec.

**Comment by bertocq** [comment] 2018-03-01 20:10
Sorry @iagirre I'm no longer available at slack since 2 weeks ago, so any questions or doubts please just comment on the issue/PR. We're trying to improve our focus and context-switching so important details don't get lost in chatrooms.

We'll have to first fix https://github.com/AyuntamientoMadrid/consul/issues/1314 before coming back to this one, and then we'll sort out those problems :) Thanks for your response!

**Comment by voodoorai2000** [comment] 2018-04-05 15:10
Good to go @iagirre https://github.com/consul/consul/pull/2552

**Comment by devinbalkind** [comment] 2018-11-07 14:51
Hi. @MatheusMiranda is tackling this as part of [MediaLab Prado Collective Intelligence program](https://www.medialab-prado.es/en/news/icdemocracia2018-collective-intelligence-reinventing-democracy). We've simplified the design a bit - placing the map on the top right of the sidebar. 

![expanding consul - media lab prado 2018](https://user-images.githubusercontent.com/444311/48138619-feac0380-e2a4-11e8-8df8-d10706bd7f26.png)

**Comment by voodoorai2000** [comment] 2018-12-19 12:13
Closed via https://github.com/consul/consul/pull/3038

**Closed by voodoorai2000** 2018-12-19 12:13 UTC
Labels: Backport, Budget, In-progress
