### ISSUE TITLE
Bug on recover password

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2179] opened 2017-12-12 17:43 UTC
We've got this bug that needs some research to find if its possible to reproduce or a human error:

> At the "recorver my password" page, I typed my new password twice and sent the form, but the next page gave me a "page can’t be found" https://decide.madrid.es/do_finish_signup 

Seems like it might be related to users that have `registering_with_oauth`

**Comment by aitbw** [comment] 2017-12-18 15:12
I'm going to check this one

**Comment by bertocq** [comment] 2018-01-15 11:13
Hey @aitbw  just wanted to check how're we going on this one. Do you have something to report or some code? Or should this be free-to-pick again? Thanks :)

**Comment by aitbw** [comment] 2018-01-15 11:52
Hey @bertocq, as today, I haven't been able to reproduce this bug locally :( so feel free to label it with `PRs-welcome`

**Comment by iagirre** [comment] 2018-01-26 10:13
I'm going to try this one.

**Comment by bertocq** [comment] 2018-01-26 10:15
@iagirre take into account that this issue was reported at madrid's fork, so maybe the problem is specific to changes/customizations done there https://github.com/ayuntamientomadrid/consul

**Comment by iagirre** [comment] 2018-01-30 08:49
I was unable to reproduce the error locally :(
I tried with the actual code from https://github.com/ayuntamientomadrid/consul and with older versions of the software, but I couldn't figure out what happened when the issue was reported.
I also tried with the code from https://github.com/consul/consul, just in case, but I found nothing.

**Comment by voodoorai2000** [comment] 2018-01-30 11:40
Alright, thanks for trying it out guys :)
We haven't received complains about this issue, maybe it has been solved in other commits.
Closing!

**Closed by voodoorai2000** 2018-01-30 11:40 UTC
Labels: Bug
