### ISSUE TITLE
Add a "Modify email" menu to the Management interface

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3546] opened 2019-05-28 09:29 UTC
## Background
The Management interface `/management/` allow the managers to do actions to help users.

## What we need
Add a new submenu titled "Modify email" to the interface. It will allow to change the email associated to the user account, to add one in case the account has no mail associated, or to delete the existing one in case the user prefer not to have any email associated to the account.

**Comment by javierm** [comment] 2019-11-13 20:21
Duplicate of #2499.

**Closed by javierm** 2019-11-13 20:21 UTC
Labels: Good first issue, help wanted
