### ISSUE TITLE
Flaky spec:  Admin budgets Manage groups and headings Create group

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2573] opened 2018-04-04 17:58 UTC
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 34049

**Travis failed build:** https://travis-ci.org/consul/consul/jobs/362251287

**Failure:**

```
    1) Admin budgets Manage groups and headings Create group
     Failure/Error: expect(page).to have_content '1 Group of budget headings'
       expected to find text "1 Group of budget headings" in "Language: English Español Français Nederlands Português CONSUL ADMINISTRATION Admin Notifications My activity My account Sign out Categories Moderated content Polls Participatory budgets Profiles Collaborative Legislation Banners Site customization Manage geozones Signature Sheets Sending of emails Go back Yearly budget 0 Groups of budget headings No groups created yet. Each user will be able to vote in only one heading per group. Add new group Group name"
     # ./spec/features/admin/budgets_spec.rb:237:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

### Final thoughts
The true objective of this issue is not "to fix" a flaky spec, but to change a spec that randomly fails into one that we can trust when it passes (or fails). 

That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".

Sometimes the fix is to re-write the entire tests with a different approach, or to extend an existing spec. Tests are sometimes written without taking a look at other tests files neither near scenarios.

**Comment by cheneyshreve** [comment] 2018-06-18 17:12
Hi @bertocq, I would like to work on this one if it available. Many thanks!

**Comment by bertocq** [comment] 2018-06-19 16:18
Sure @cheneyshreve!! 👏Go for it :), although this one is flaky spec report is almost 3 months old so keep in mind it might have been already fixed.

**Comment by cheneyshreve** [comment] 2018-06-22 18:32
Hi @bertocq , I have been looking at the investments_spec error. It appears the original flaky spec error has been resolved (steps, results outlined below). However, running the full investment_spec multiple times (with different seeds) consistently shows 2 new errors (shown at end of comment). 

So perhaps it is possible to close this issue, and maybe open a different one to look at the 2 new errors? I’d be happy to work on that one if you’d like. 

With random seed that was questioned for flaky spec specified
for run in {1..10}
do
  rspec spec/features/budgets/investments_spec.rb:256 --seed 34049
done

Without the random seed specified
for run in {1..10}
do
  rspec spec/features/budgets/investments_spec.rb:256 
done

Both results have 0 failures

I then ran the full test 10 times to double check, since have been modified in the last 3 months. 
for run in {1..10}
do
  rspec spec/features/budgets/investments_spec.rb
done

Consistently returns these 2 errors:
Failures:

  1) Budgets In Drafting phase Shown Not accesible to logged users
     Failure/Error: expect { visit budget_path(budget) }.to raise_error(ActionController::RoutingError)
       expected ActionController::RoutingError but nothing was raised
      ./spec/features/budgets/budgets_spec.rb:410:in `block (4 levels) in <top (required)>'

  2) Budgets In Drafting phase Shown Not accesible to guest users
     Failure/Error: expect { visit budget_path(budget) }.to raise_error(ActionController::RoutingError)
       expected ActionController::RoutingError but nothing was raised
      ./spec/features/budgets/budgets_spec.rb:404:in `block (4 levels) in <top (required)>'

rspec ./spec/features/budgets/budgets_spec.rb:403 # Budgets In Drafting phase Shown Not accesible to guest users

Here are the random seeds that were used: 45704, 934, 58726, 58726, 59823,9123,38735,13735,46814

**Comment by javierv** [comment] 2018-06-23 00:10
Hi, @cheneyshreve. If I understand correctly, you can't reproduce the failure affecting the spec mentioned on this issue, right?

On my machine, after a couple of changes it fails about a third of the time, so if you don't mind I can give it a look.

**Comment by cheneyshreve** [comment] 2018-06-23 00:15
HI @javierv, yes, you are correct, I cannot reproduce that error. It passes on my machine. Sounds like it is still an issue though if you are seeing errors!

**Comment by javierv** [comment] 2018-06-23 00:54
It seems to be related to the `toggleLink` function in `App.forms`. On my machine, changing `.toggle("down")` to `.show()` makes the test pass 100% of the time, but that's obviously not a good solution. I'll keep looking.

**Comment by cheneyshreve** [comment] 2018-06-23 01:07
@javierv  I'm working on a Mac OSX, what machine are you using? Did you fetch the most recent changes from upstream and still see error? Not sure why it doesn't show up on my machine, just trying to trouble shoot--thanks for also taking a look :)

**Comment by javierv** [comment] 2018-06-23 01:12
@cheneyshreve I'm using the current master branch (is it the right branch to be on? HEAD is on a8178a6 ), on Ubuntu 16.04.

**Comment by cheneyshreve** [comment] 2018-06-23 02:08
@javierv, thanks, we can keep adding details. Perhaps it's difference in our machines setups; I'm using ChromeDriver 2.4

**Comment by javierv** [comment] 2018-06-23 16:14
Hi, @cheneyshreve. I've just realized we're running different specs :). The one I'm running is "Admin budgets Manage groups and headings Create group", which is around `spec/features/admin/budgets_spec.rb:237` (as described in the "what" section). It looks like the code in "random values issues" was copied from somewhere else, and mentions the one you're running, which is `spec/features/budgets/investments_spec.rb:256`.

Hope you can now reproduce the failure on your machine!

P.S. For the record, on my machine it fails with ChromeDriver 2.40 as well.

**Comment by MariaCheca** [comment] 2018-08-10 11:15
Closed via https://github.com/consul/consul/pull/2696

**Closed by MariaCheca** 2018-08-10 11:15 UTC
Labels: Flaky spec, PRs-welcome
