### ISSUE TITLE
Polls results when online voting

### ISSUE THREAD

**Issue by smarques** [consul/consul#3964] opened 2020-04-06 16:16 UTC
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As an admin I want to be able to create online-only polls, and see and publish the results

### Why is this Needed?

[comment]: # We would like to use Consul as an online consultation system for a civic group

### Description

This seems like a bug to me..
I can create a poll, add questions and possible answers, have people vote on line, but I can not find a way to view and publish the results.
When I look at the code I see there is a display of partial results that seem to be only associated via booth_assignments

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Nothis is displayed when I click on the results section of the poll, only the form to publish them

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
I expect to see the current results for the specific poll

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)
Create a poll, add one question with two possible answers
Have a few users vote them
go in the admin section, go to the specific poll, click results

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment] 2020-04-08 02:38
Hi, @smarques :smile:.

Results are publicly available once the poll is finished and the "show results" option has been selected in the form you mention.

In the admin section results are shown by booth, as a tool to help verifying manual recounts. Online votes aren't counted manually, so they aren't shown there.

**Comment by javierm** [comment] 2020-04-16 17:09
Closing this one since it looks like it works as intended. @smarques Feel free to reopen if you think my previous answer wasn't satisfactory :wink:.

**Closed by javierm** 2020-04-16 17:09 UTC

**Comment by smarques** [comment] 2020-04-26 16:02
Confirm it works as intended. Thank you.
