### ISSUE TITLE
SocketError - Error 500 sending emails

### ISSUE THREAD

**Issue by jovanovski** [consul/consul#3391] opened 2019-03-20 11:41 UTC
Hey all, when I try to reset a user password, I get this issue and a 500 page. I am now locked out of my admin account whose password I tried to change. 

I am guessing it's failing when trying to send an email, but not sure what to do at this state.

Fresh Ubuntu 16.04 x64 on DigitalOcean, installed via consul installer.

```
W, [2019-03-20T12:32:10.390722 #3504]  WARN -- : [Rollbar] Got unexpected status code from Rollbar api: 400
W, [2019-03-20T12:32:10.632281 #3504]  WARN -- : [Rollbar] Got unexpected status code from Rollbar api: 400
F, [2019-03-20T12:32:10.636652 #3504] FATAL -- :
SocketError (getaddrinfo: Name or service not known):
  socksify (1.7.1) lib/socksify.rb:178:in `initialize'
  socksify (1.7.1) lib/socksify.rb:178:in `initialize'
  /home/deploy/.rvm/rubies/ruby-2.3.2/lib/ruby/2.3.0/net/smtp.rb:542:in `open'
  /home/deploy/.rvm/rubies/ruby-2.3.2/lib/ruby/2.3.0/net/smtp.rb:542:in `tcp_socket'
  /home/deploy/.rvm/rubies/ruby-2.3.2/lib/ruby/2.3.0/net/smtp.rb:552:in `block in do_start'
  /home/deploy/.rvm/rubies/ruby-2.3.2/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
  /home/deploy/.rvm/rubies/ruby-2.3.2/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
  /home/deploy/.rvm/rubies/ruby-2.3.2/lib/ruby/2.3.0/net/smtp.rb:551:in `do_start'
  /home/deploy/.rvm/rubies/ruby-2.3.2/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
  mail (2.7.1) lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
  mail (2.7.1) lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
  mail (2.7.1) lib/mail/message.rb:2159:in `do_delivery'
  mail (2.7.1) lib/mail/message.rb:260:in `block in deliver'
  actionmailer (4.2.11.1) lib/action_mailer/base.rb:543:in `block in deliver_mail'
  activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.11.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `instrument'
  actionmailer (4.2.11.1) lib/action_mailer/base.rb:541:in `deliver_mail'
  mail (2.7.1) lib/mail/message.rb:260:in `deliver'
  actionmailer (4.2.11.1) lib/action_mailer/message_delivery.rb:85:in `deliver_now'
  devise-async (0.10.2) lib/devise/async/backend/base.rb:21:in `block in perform'
  i18n (0.9.5) lib/i18n.rb:268:in `with_locale'
  devise-async (0.10.2) lib/devise/async/backend/base.rb:17:in `perform'
  delayed_job (4.1.5) lib/delayed/performable_method.rb:26:in `perform'
  delayed_job (4.1.5) lib/delayed/backend/base.rb:81:in `block in invoke_job'
  rollbar (2.18.0) lib/rollbar/plugins/delayed_job/plugin.rb:39:in `block in invoke_job_callback'
  delayed_job (4.1.5) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  delayed_job (4.1.5) lib/delayed/lifecycle.rb:61:in `block in initialize'
  delayed_job (4.1.5) lib/delayed/lifecycle.rb:79:in `block in add'
  delayed_job (4.1.5) lib/delayed/lifecycle.rb:66:in `execute'
  delayed_job (4.1.5) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  delayed_job (4.1.5) lib/delayed/backend/base.rb:78:in `invoke_job'
  delayed_job (4.1.5) lib/delayed/backend/base.rb:19:in `block (2 levels) in enqueue_job'
  delayed_job (4.1.5) lib/delayed/lifecycle.rb:61:in `block in initialize'
  delayed_job (4.1.5) lib/delayed/lifecycle.rb:66:in `execute'
  delayed_job (4.1.5) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  delayed_job (4.1.5) lib/delayed/backend/base.rb:17:in `block in enqueue_job'
  delayed_job (4.1.5) lib/delayed/backend/base.rb:16:in `tap'
  delayed_job (4.1.5) lib/delayed/backend/base.rb:16:in `enqueue_job'
  delayed_job (4.1.5) lib/delayed/backend/base.rb:12:in `enqueue'
  delayed_job (4.1.5) lib/delayed/message_sending.rb:11:in `method_missing'
  devise-async (0.10.2) lib/devise/async/backend/delayed_job.rb:6:in `enqueue'
  devise-async (0.10.2) lib/devise/async/worker.rb:11:in `enqueue'
  devise-async (0.10.2) lib/devise/async/model.rb:43:in `send_devise_notification'
  devise (3.5.10) lib/devise/models/recoverable.rb:107:in `send_reset_password_instructions_notification'
  devise (3.5.10) lib/devise/models/recoverable.rb:60:in `send_reset_password_instructions'
  devise (3.5.10) lib/devise/models/recoverable.rb:124:in `send_reset_password_instructions'
  devise (3.5.10) app/controllers/devise/passwords_controller.rb:13:in `create'
  actionpack (4.2.11.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.11.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.11.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.11.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.11.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.11.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.11.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.11.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.11.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.11.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.11.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.11.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.11.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.11.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.11.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  turnout (2.4.0) lib/rack/turnout.rb:25:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
  omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
  omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
  omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack-attack (5.0.1) lib/rack/attack.rb:147:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.11) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.11) lib/rack/conditionalget.rb:38:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.11) lib/rack/head.rb:13:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.11) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.11) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activerecord (4.2.11.1) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activerecord (4.2.11.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rollbar (2.18.0) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
  rollbar (2.18.0) lib/rollbar.rb:146:in `scoped'
  rollbar (2.18.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rollbar (2.18.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  railties (4.2.11.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.11.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.11.1) lib/rails/rack/logger.rb:20:in `call'
  ahoy_matey (1.6.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.11) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activesupport (4.2.11.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  railties (4.2.11.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.11.1) lib/rails/application.rb:165:in `call'
  newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  unicorn (5.4.1) lib/unicorn/http_server.rb:606:in `process_client'
  unicorn (5.4.1) lib/unicorn/http_server.rb:701:in `worker_loop'
  unicorn (5.4.1) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
  unicorn (5.4.1) lib/unicorn/http_server.rb:142:in `start'
  unicorn (5.4.1) bin/unicorn:126:in `<top (required)>'
  /home/deploy/.rvm/gems/ruby-2.3.2/bin/unicorn:22:in `load'
  /home/deploy/.rvm/gems/ruby-2.3.2/bin/unicorn:22:in `<main>'
  /home/deploy/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `eval'
  /home/deploy/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by luis30n** [comment] 2019-09-24 16:58
It seems like you have to add your workstation name to /etc/hosts 127.0.0.1 but it does not work for me so far

**Comment by javierm** [comment] 2019-10-18 15:44
@jovanovski Does the application send emails properly? It looks like an error with SMTP. Have you configured your SMTP settings?

**Comment by javierm** [comment] 2020-04-06 17:58
Closing since the cause seems to be SMTP not being configured propery and CONSUL now enables delayed jobs by default (https://github.com/consul/installer/pull/103), so the application won't crash when emalis cannot be sent.

**Closed by javierm** 2020-04-06 17:58 UTC
