### ISSUE TITLE
Newsletter editor doesn't appear on Safari

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#3903] opened 2020-01-20 06:48 UTC
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

The newsletter editor doesn't appear on Safari (latest on Mac and iOS) and the following message is given in the console: `The editor instance "newsletter_body" is already attached to the provided element.`

The editor appears on Chrome and Firefox so this should be considered low priority, even though Safari has an important market share in some countries when combining desktop and mobile devices.

**Comment by javierm** [comment] 2020-04-06 17:33
@PierreMesure Thanks for reporting. Does it happen in other places where we use CKEditor?

**Comment by PierreMesure** [comment] 2020-04-06 17:54
Not that I know of.

**Comment by javierm** [comment] 2020-05-01 10:17
I can reproduce a similar behavior with Firefox:

1. Go to a page loading CKEditor, like the newsletter editor
2. Click somewhere else in order to leave the page
3. Click the browser's back button

CKEditor will appear empty, it will be impossible to edit its content, and clicking any toolbar button will raise a JavaScript error.

**Comment by javierm** [comment] 2020-05-01 17:40
@PierreMesure Since I don't use Safari, and I get inconsistent results with Firefox, could you do me a favor? :pray:

Could you confirm you can still reproduce the issue in the `master` branch?

Could you check whether removing `app/assets/javascripts/ckeditor/reinit.js` solves the problem?

Thanks!

**Comment by Senen** [comment] 2020-05-05 10:09
Hi there! 👋 

I am having the same behavior than @javierm, cannot edit ckeditor contents when using browser history back to go back a page with ckeditor. This is currently happening with Firefox, Safari and Chrome. I am currently working on a patch.

I was not able to reproduce the error described by @PierreMesure using Safari at current master branch. Let's wait for Pierre confirmation also!

**Comment by PierreMesure** [comment] 2020-05-06 09:46
I just tested and I now see the CKEditor on the Newsletter creation/edition page. Plus no message in the console anymore.

I can also reproduce the behaviour you mention on Safari:
- blank and blocked editor when leaving the page and coming back
- no editor at all when closing the tab and opening it again (Cmd-Z on Safari)

**Comment by Senen** [comment] 2020-05-06 09:50
Thanks @PierreMesure for re-checking this , now we are on the same page!

**Comment by javierm** [comment] 2020-05-11 12:59
Closing this one since the original issue cannot be reproduced and the other issue mentioned in the comments is solved by #3998.

**Closed by javierm** 2020-05-11 12:59 UTC
Labels: Bug
