### ISSUE TITLE
Configure with nginx and passenger

### ISSUE THREAD

**Issue by jfoclpf** [consul/consul#4240] opened 2020-11-08 23:41 UTC
I've been through the installation process and everything is running fine
I do `bin/rails s` and it works

Can someone just give me now a typical nginx configuration file with passenger?
I have this but it does not work

```
server {

    server_name decidelisboa.org;
    #client_max_body_size 32M;

    passenger_enabled on;
    passenger_ruby /home/jfolpf/.rbenv/shims/ruby;

    #rails_env    production;
    root         /var/www/consul-lisboa/public;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/decidelisboa.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/decidelisboa.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = decidelisboa.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80 ipv6only=on;

    server_name decidelisboa.org;
    return 404; # managed by Certbot

}
```

thanks a lot

**Comment by jfoclpf** [comment] 2020-11-09 00:02
Found it, I had to change this line to

`rails_env    development;`

btw, this project does not support `production`? I don't see production in `Gemfile`

**Comment by javierm** [comment] 2020-11-09 11:30
Hi, @jfoclpf :smile:.

When the environment is not specified in the Gemfile, the gem is installed on all environments (including production). Gems listed in a block using `group :development` are only installed in the development environment.

```
rails_env development;
```

If you needed to add this line, I think something hasn't gone so well in the installation process :thinking:. Running a production server using the development environment is not recommended as it might have plenty of side effects.

**Comment by jfoclpf** [comment] 2020-11-09 12:04
Hi @javierm 
Thanks for the reply. You have to give me some tips here cause I'm not versed in ruby ;)

So, I forked consul and then I did from my forked repo

```
git clone https://github.com/jfoclpf/consul-lisboa.git
cd consul
bundle install
cp config/database.yml.example config/database.yml
cp config/secrets.yml.example config/secrets.yml
bin/rake db:create
bin/rake db:migrate
bin/rake db:dev_seed
RAILS_ENV=test rake db:setup
```

Then I restarted nginx with that above config file and it works.

What do I need exactly to install the production version? Just change the value of `RAILS_ENV`?

**Comment by jfoclpf** [comment] 2020-11-09 12:52
I mean, the manual installation [instructions](https://docs.consulproject.org/docs/) are very good
I just need instructions on how to do manual installation on production. Sorry, I don't want to run an automatic installer, I'm afraid that is gonna mess with my server. 

Now, I'm trying to run production and I get this error:
`Incomplete response received from application`

**Comment by javierm** [comment] 2020-11-09 16:34
I understand you're trying to apply the same instructions used for development environments to production environments.

I'm afraid that won't work. Installation on a production environment requires different installer. A mentioned in consul/docs#98, have a look at the installer's code. Hope that helps!

Closing as duplicate of consul/docs#98.

**Closed by javierm** 2020-11-09 16:34 UTC
