### ISSUE TITLE
Main fonts have only latin letters

### ISSUE THREAD

**Issue by ppeczek** [consul/consul#3372] opened 2019-03-17 18:13 UTC
Any nonlatin letter language needs to override fonts right now with the same font families containing their native letters. This could be easily fixed by loading multi-language asset.

**Comment by javierm** [comment] 2019-10-19 01:47
@ppeczek I can't reproduce this issue. Chinese looks fine on my machine :thinking:.

![CONSUL in Chinese, with Chinese characters](https://user-images.githubusercontent.com/35156/67136182-0bf69f80-f223-11e9-90fe-e044fff978f6.png)

**Comment by javierm** [comment] 2019-11-19 02:28
@ppeczek I think I'd need some help to reproduce it. Could you add more information, like which system you're using, a screenshot of what you see, ...? Thanks! :pray:

**Comment by javierm** [comment] 2020-04-06 17:54
Closing since I can't reproduce the issue and no further information was provided.

**Closed by javierm** 2020-04-06 17:54 UTC
