### ISSUE TITLE
Fix SCSS Lint issues

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2272] opened 2018-01-07 12:12 UTC
What we need
==

By running `scss-lint` on your terminal at the root directory of the proyect you'll see multiple warnings thrown by the tool that should be fixed:
```
pp/assets/stylesheets/legislation_process.scss:413:11 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:463:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:467:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:477:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:523:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:586:11 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:604:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:637:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:642:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:646:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:652:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:657:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:661:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 7
app/assets/stylesheets/legislation_process.scss:668:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:671:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:676:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:679:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:687:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:693:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:703:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 7
app/assets/stylesheets/legislation_process.scss:707:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 7
app/assets/stylesheets/legislation_process.scss:713:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:724:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:725:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 7
app/assets/stylesheets/legislation_process.scss:734:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
app/assets/stylesheets/legislation_process.scss:740:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:743:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 7
app/assets/stylesheets/legislation_process.scss:747:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 7
app/assets/stylesheets/legislation_process.scss:753:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 6
app/assets/stylesheets/legislation_process.scss:755:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 7
app/assets/stylesheets/legislation_process.scss:758:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 8
app/assets/stylesheets/legislation_process.scss:761:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 8
app/assets/stylesheets/legislation_process.scss:767:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 8
app/assets/stylesheets/legislation_process.scss:772:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 7
app/assets/stylesheets/legislation_process.scss:777:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 8
app/assets/stylesheets/legislation_process.scss:781:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 8
app/assets/stylesheets/legislation_process.scss:787:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 8
app/assets/stylesheets/legislation_process.scss:792:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 8
app/assets/stylesheets/legislation_process.scss:799:1 [W] SelectorDepth: Selector should have depth of applicability no greater than 5, but was 8
app/assets/stylesheets/legislation_process.scss:811:9 [W] NestingDepth: Nesting should be no greater than 4, but was 5
```

**Comment by javierm** [comment] 2019-11-13 19:48
Duplicate of #1676.

**Closed by javierm** 2019-11-13 19:48 UTC
Labels: help wanted
